---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/RedundantStringEscape:
  Exclude:
  - spec/lib/eac_config/paths_hash_spec.rb
Style/SelectByRegexp:
  Exclude:
  - lib/eac_config/yaml_file_node/self_entries.rb
Style/SlicingWithRange:
  Exclude:
  - lib/eac_config/paths_hash/path_search.rb
Style/StringConcatenation:
  Exclude:
  - spec/lib/eac_config/yaml_file_node_spec.rb
